language: python
sudo: required
dist: xenial
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - make env
  - ln -s $(realpath .drivers/geckodriver-linux64) .drivers/geckodriver
script: PATH="$(pwd)/.drivers:$PATH" python src/manage.py test app
branches:
  only:
    - master
